import { emptyEntry, type Entry } from "./model";
const work = (
  id: string,
  title: string,
  description: string,
  category: string,
  techStack: string[],
  date: string,
): Entry => ({
  ...emptyEntry("works"),
  id,
  slug: id,
  title,
  description,
  category,
  techStack,
  eyecatch: `/images/${id}.svg`,
  imageAlt: `${title}の画面イメージ`,
  authorName: "DataDreamers 制作メンバー",
  clerkUserId: "demo-editor",
  status: "published",
  createdAt: date,
  updatedAt: date,
  publishedAt: date,
  version: 1,
  content: `## つくったきっかけ\n${description}\n\n身近な「少し不便だな」という場面から、制作を始めました。まず小さく動くものをつくり、メンバー同士で触りながら改善しています。\n\n## 使い方\n画面の案内に沿って操作できます。下の「この作品を起動する」から、サンプルを試してみてください。\n\n## 工夫したところ\n- 初めて使う人が迷わない、シンプルな画面\n- スマートフォンでも操作できるボタンの大きさ\n- 入力を間違えたときに戻れる設計\n\n※この作品はサイトの動作確認用サンプルです。実際の活動実績ではありません。`,
  appUrl: "/demos/timer.html",
  displayMode: "iframe",
  embedStatus: "allowed",
});
export const seed: Entry[] = [
  {
    ...work(
      "campus-map",
      "空いてる場所、ひと目で。",
      "「今、どこで作業しよう？」を解決する、学内施設の混雑マップ。教室や自習スペースの状況を見渡せます。",
      "Webアプリ",
      ["Next.js", "TypeScript", "Cloudflare"],
      "2026-09-02T09:00:00.000Z",
    ),
    appUrl: "/demos/campus.html",
  },
  work(
    "study-timer",
    "ひと区切りタイマー",
    "25分だけ、目の前のことに集中する。勉強仲間と考えた、必要な機能だけの学習タイマー。",
    "学習ツール",
    ["React", "CSS"],
    "2026-08-28T09:00:00.000Z",
  ),
  {
    ...work(
      "class-vote",
      "みんなで決める投票箱",
      "文化祭の出し物から、次の勉強会のテーマまで。小さなチームで使う、気軽な投票アプリ。",
      "Webアプリ",
      ["JavaScript", "Cloudflare D1"],
      "2026-08-21T09:00:00.000Z",
    ),
    appUrl: "/demos/vote.html",
  },
  ...[
    [
      "first-map",
      "教室を歩いて、マップをつくる。",
      "画面の前を離れて、まずは学内を一周。場所を調べるところから始めた制作の記録です。",
      "制作ノート",
      "2026-09-01",
    ],
    [
      "summer-review",
      "夏休みの制作、持ち寄りました。",
      "つくりかけのものも、そのままで。お互いの画面を見ながら、次に直したいところを話しました。",
      "活動記録",
      "2026-08-29",
    ],
    [
      "first-git",
      "はじめての共同開発と、Gitのこと。",
      "ブランチを分ける理由が、ようやく分かった日。小さな失敗から覚えたことをまとめます。",
      "技術メモ",
      "2026-08-23",
    ],
    [
      "timer-note",
      "機能を減らしたら、使いやすくなった。",
      "タイマーに本当に必要なものは何だろう。メンバーに試してもらって、考え直しました。",
      "制作ノート",
      "2026-08-18",
    ],
  ].map(([id, title, description, category, date], i): Entry => ({
    ...emptyEntry("articles"),
    id,
    slug: id,
    title,
    description,
    category,
    eyecatch: `/images/${i === 0 ? "field-notes" : i === 1 ? "summer-review" : i === 2 ? "git-notes" : "study-timer"}.svg`,
    imageAlt: title + "の制作イメージ",
    authorName: "DataDreamers 編集メンバー",
    clerkUserId: i === 1 ? "demo-admin" : "demo-editor",
    status: "published",
    createdAt: date + "T09:00:00.000Z",
    updatedAt: date + "T09:00:00.000Z",
    publishedAt: date + "T09:00:00.000Z",
    version: 1,
    content: `## ${i === 0 ? "まず、現場を見てみる" : "つくりながら、考えたこと"}\n${description}\n\nDataDreamersでは、身近な課題を見つけ、小さなアプリにしてみるところから制作を始めています。今回も、最初から完成形が見えていたわけではありません。\n\n## 触ってもらって分かったこと\n自分にとって当たり前の操作でも、初めて見る人には伝わらないことがあります。説明する前に使ってもらうと、思いがけない場所で手が止まりました。\n\n- ボタンの言葉は、操作の結果が分かるようにする\n- 情報を増やす前に、今ある情報の順番を見直す\n- 迷ったところを記録して、次の制作に持ち帰る\n\n## 次にやってみたいこと\n**小さくつくって、試して、直す。** この繰り返しを大事にしながら、もう少し使いやすくしていきたいです。\n\n※この記事はサイトの表示確認用サンプルです。実際の活動記録ではありません。`,
  })),
];
