CREATE TABLE IF NOT EXISTS members (id TEXT PRIMARY KEY, name TEXT NOT NULL, role TEXT NOT NULL CHECK(role IN ('editor','admin')));
CREATE TABLE IF NOT EXISTS rate_limits (key TEXT PRIMARY KEY, count INTEGER NOT NULL, expires INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS posts (id TEXT PRIMARY KEY, kind TEXT NOT NULL, slug TEXT NOT NULL, owner TEXT NOT NULL, version INTEGER NOT NULL DEFAULT 0, status TEXT NOT NULL DEFAULT 'draft', updated TEXT NOT NULL, lock_id TEXT, UNIQUE(kind,slug));
CREATE TABLE IF NOT EXISTS requests (key TEXT PRIMARY KEY, hash TEXT NOT NULL, post_id TEXT NOT NULL, state TEXT NOT NULL DEFAULT 'pending', response TEXT, created INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS posts_owner ON posts(owner);
CREATE TABLE IF NOT EXISTS slugs (kind TEXT NOT NULL, slug TEXT NOT NULL, post_id TEXT NOT NULL, PRIMARY KEY(kind,slug));
